version: "1"

services:
  mysql:
    image: mysql:8.0.26
    container_name: database-mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=Unu#2024
    ports:
    - 3307:3306
    - 33061:33060
    networks:
    - tda2024 
    
networks:
  tda2024:
    name: taller-final