server:
  port: 6001
  
jwt:
  secret: Bx4MeizkOfmx5buS0AeRdfWkK1H4GI8abShDqtZq6gA=
  
spring:
  application:
    name: appgateway
  cloud:
   gateway:
    discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
        default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
    routes:      
      
      - id: MsUsuario
        uri: http://localhost:8084
        predicates:
            - Path=/auth/**
      - id: MSMatricula
        uri: http://localhost:87
        predicates:
            - Path=/auth/**
      - id: MsEstudiante
        uri: http://localhost:8081
        predicates:
            - Path=/auth/**
 