spring:
  cloud:
    gateway:
      routes:
        - id: msusuario-login
          uri: http://localhost:8081  # Cambiado al puerto 8081 de MsUsuario
          predicates:
            - Path=/auth/login       # Ruta de login que ser치 redirigida a MsUsuario
          filters:
            - AddRequestHeader=X-Request-Foo, Bar   # (Opcional) Ejemplo de filtro de cabecera

        - id: msusuario-register
          uri: http://localhost:8081  # Cambiado al puerto 8081 de MsUsuario
          predicates:
            - Path=/auth/register    # Ruta de registro que ser치 redirigida a MsUsuario
          filters:
            - AddRequestHeader=X-Request-Foo, Bar   # (Opcional) Ejemplo de filtro de cabecera

      # Otras configuraciones generales del Gateway, por ejemplo:
      default-filters:
        - name: RequestTimeFilter   # Filtro predeterminado para agregar tiempos de solicitud

      # Configuraci칩n de puerto para el Gateway (opcional, si no tienes otra configuraci칩n)
      server:
        port: 8080  # El puerto del Gateway


