server:
  port: 6001

jwt:
  secret: Key#SuperSecret$PolyglotTest#JavaMicroservices#940527000

spring:
  application:
    name: appgateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:      
      - id: appseguridad
        uri: http://localhost:85
        predicates:
          - Path=/security/**
        filters:
          - StripPrefix=1
      - id: appdeposit
        uri: http://localhost:86
        predicates:
          - Path=/deposit/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
      - id: appaccount
        uri: http://localhost:87
        predicates:
          - Path=/account/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
      - id: apptransaction
        uri: http://localhost:88
        predicates:
          - Path=/transaction/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
           
  
